import Head from 'next/head'
import Link from 'next/link'
import Layout from '../../components/Layout'

export default function Articles({articles}) {


  return (
    <Layout>
      <Head>
        <title>Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Articles
      </h1>
      <ul>
        {articles.map( article => (
          <li key={article.slug} className="my-5">
            <h2 className="font-bold mb-1"><Link href={`/articles/${article.slug}`}>{article.title}</Link></h2>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export const getStaticProps = async () => {
    const res = await fetch('http://localhost:3000/api/articles')
    const articles = await res.json();
    return {
        props : {articles}
    }
}